<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">containsOnly</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJdmFsaWRDaGFycyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAidmFsaWRDaGFycyIgKTsKCQoKCWJvb2xlYW4gdmFsdWUgPSBTdHJpbmdVdGlscy5jb250
YWluc09ubHkoc3RyLCB2YWxpZENoYXJzKTsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEg
PSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEs
ICJ2YWx1ZSIsIHZhbHVlICk7CgoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cn0KY2F0Y2go
RXhjZXB0aW9uIGUpCnsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9Cg==</value>
</Values>
