<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">centerWithString</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CQoJU3RyaW5nCXBhZFN0ciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAicGFkU3RyIiApOwkKCWludAlzaXplID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJz
b3IsICJzaXplIiwgMCApOwoKCVN0cmluZyB2YWx1ZSA9IFN0cmluZ1V0aWxzLmNlbnRlcihzdHIs
IHNpemUsIAlwYWRTdHIpOwoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5l
LmdldEN1cnNvcigpOwoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInZhbHVlIiwg
dmFsdWUgKTsKCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChFeGNlcHRpb24g
ZSkKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
