<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substringBetweenTag</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJdGFnID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJ0
YWciICk7CgkKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5zdWJzdHJpbmdCZXR3ZWVuKHN0
ciwgdGFnKTsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ2YWx1ZSIsIHZhbHVlICk7
CgoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0aW9uIGUpCnsKCXRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9Cg==</value>
</Values>
