<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compareDoubles</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQp0cnkNCnsNCglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNv
cigpOw0KCWRvdWJsZQlsaHMgPSBOdW1iZXJVdGlscy5jcmVhdGVEb3VibGUoSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJsaHMiICkpOwkJCQkNCglkb3VibGUJcmhzID0gTnVt
YmVyVXRpbHMuY3JlYXRlRG91YmxlKElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAicmhzIiApKTsNCgkJCQ0KCWludCB2YWx1ZSA9IE51bWJlclV0aWxzLmNvbXBhcmUobGhzLCBy
aHMpOw0KCQ0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUiLCB2YWx1ZSAp
Ow0KDQoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQp9DQpjYXRjaChFeGNlcHRpb24gZSkN
CnsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsNCn0J</value>
</Values>
