<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">indexOfAnyStringArray</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmdbXQlzZWFyY2hTdHJzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KCBwaXBl
bGluZUN1cnNvciwgInNlYXJjaFN0cnMiICk7CgkKCglpbnQgaW5kZXggPSBTdHJpbmdVdGlscy5p
bmRleE9mQW55KHN0ciwgc2VhcmNoU3Rycyk7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8x
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8x
LCAiaW5kZXgiLCBpbmRleCApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNo
KEV4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
