<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">joinWithSeparator</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmdbXSBhcnJheSA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheSggcGlwZWxpbmVDdXJz
b3IsICJhcnJheSIgKTsKCVN0cmluZyBzZXBhcmF0b3IgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBw
aXBlbGluZUN1cnNvciwgInNlcGFyYXRvciIgKTsKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGls
cy5qb2luKGFycmF5LCBzZXBhcmF0b3IpOwoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwg
InZhbHVlIiwgdmFsdWUgKTsKCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChF
eGNlcHRpb24gZSkKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
