<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">splitPreserveAllTokensWithSeparator</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc2VwYXJhdG9yQ2hhcnMgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgInNlcGFyYXRvckNoYXJzIiApOwoKCVN0cmluZ1tdIHZhbHVlID0gU3RyaW5nVXRp
bHMuc3BsaXRQcmVzZXJ2ZUFsbFRva2VucyhzdHIsIHNlcGFyYXRvckNoYXJzKTsKCUlEYXRhQ3Vy
c29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCUlEYXRhVXRpbC5w
dXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ2YWx1ZSIsIHZhbHVlICk7CgoJcGlwZWxpbmVDdXJzb3Jf
MS5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0aW9uIGUpCnsKCXRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKGUpOwp9Cg==</value>
</Values>
