<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">wrapMultipleLines</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsNCglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJz
dHIiICk7CQkNCglTdHJpbmcJbmV3TGluZVN0ciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVs
aW5lQ3Vyc29yLCAibmV3TGluZVN0ciIgKTsNCglpbnQgd3JhcExlbmd0aCA9IElEYXRhVXRpbC5n
ZXRJbnQocGlwZWxpbmVDdXJzb3IsICJ3cmFwTGVuZ3RoIiwgMCk7CQkNCglib29sZWFuIHdyYXBM
b25nV29yZHMgPSBJRGF0YVV0aWwuZ2V0Qm9vbGVhbihwaXBlbGluZUN1cnNvciwgIndyYXBMb25n
V29yZHMiKTsNCgkNCglTdHJpbmcgdmFsdWUgPSBXb3JkVXRpbHMud3JhcChzdHIsd3JhcExlbmd0
aCwgbmV3TGluZVN0ciwgd3JhcExvbmdXb3Jkcyk7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJz
b3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yXzEsICJ2YWx1ZSIsIHZhbHVlICk7DQoNCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsN
Cn0NCmNhdGNoKEV4Y2VwdGlvbiBlKQ0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUp
Ow0KfQ0KCQ==</value>
</Values>
