<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">rightPadWithString</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CQoJU3RyaW5nCXBhZFN0ciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAicGFkU3RyIiApOwkKCWludAlzaXplID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJz
b3IsICJzaXplIiwgMCApOwoKCVN0cmluZyB2YWx1ZSA9IFN0cmluZ1V0aWxzLnJpZ2h0UGFkKHN0
ciwgc2l6ZSwgCXBhZFN0cik7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUi
LCB2YWx1ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4Y2VwdGlv
biBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
