<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">leftPadWithString</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CQoJU3RyaW5nCXBhZFN0ciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAicGFkU3RyIiApOwkKCWludAlzaXplID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJz
b3IsICJzaXplIiwgMCApOwoKCVN0cmluZyB2YWx1ZSA9IFN0cmluZ1V0aWxzLmxlZnRQYWQoc3Ry
LCBzaXplLCAJcGFkU3RyKTsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGlu
ZS5nZXRDdXJzb3IoKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ2YWx1ZSIs
IHZhbHVlICk7CgoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0aW9u
IGUpCnsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9Cg==</value>
</Values>
