<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">capitalizeWithDelimiters</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsNCglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJz
dHIiICk7DQoJU3RyaW5nW10gZGVsaW1pdGVycyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShw
aXBlbGluZUN1cnNvciwgImRlbGltaXRlcnMiKTsNCg0KCWNoYXJbXSBkZWxpbWl0ZXJzQ2hhciA9
IG5ldyBjaGFyW2RlbGltaXRlcnMubGVuZ3RoXTsNCglmb3IgKGludCBpPTA7IGk8ZGVsaW1pdGVy
cy5sZW5ndGg7IGkrKyl7DQoJCWRlbGltaXRlcnNDaGFyW2ldID0gZGVsaW1pdGVyc1tpXS5jaGFy
QXQoMCk7DQoJfQ0KCVN0cmluZyB2YWx1ZSA9IFdvcmRVdGlscy5jYXBpdGFsaXplKHN0ciwgZGVs
aW1pdGVyc0NoYXIpOw0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUiLCB2
YWx1ZSApOw0KDQoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQp9DQpjYXRjaChFeGNlcHRp
b24gZSkNCnsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsNCn0=</value>
</Values>
