<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stripStart</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc3RyaXBDaGFycyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAic3RyaXBDaGFycyIgKTsKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5zdHJpcFN0
YXJ0KHN0ciwgc3RyaXBDaGFycyk7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFs
dWUiLCB2YWx1ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4Y2Vw
dGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
