<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">uncapitalizeWithDelimiters</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsNCglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJz
dHIiICk7DQoJU3RyaW5nW10gZGVsaW1pdGVycyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShw
aXBlbGluZUN1cnNvciwgImRlbGltaXRlcnMiKTsNCg0KCWNoYXJbXSBkZWxpbWl0ZXJzQ2hhciA9
IG5ldyBjaGFyW2RlbGltaXRlcnMubGVuZ3RoXTsNCglmb3IgKGludCBpPTA7IGk8ZGVsaW1pdGVy
cy5sZW5ndGg7IGkrKyl7DQoJCWRlbGltaXRlcnNDaGFyW2ldID0gZGVsaW1pdGVyc1tpXS5jaGFy
QXQoMCk7DQoJfQ0KCVN0cmluZyB2YWx1ZSA9IFdvcmRVdGlscy51bmNhcGl0YWxpemUoc3RyLCBk
ZWxpbWl0ZXJzQ2hhcik7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5l
LmdldEN1cnNvcigpOw0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ2YWx1ZSIs
IHZhbHVlICk7DQoNCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCn0NCmNhdGNoKEV4Y2Vw
dGlvbiBlKQ0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0KfQ==</value>
</Values>
