<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substringBefore</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc2VwYXJhdG9yID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJzZXBhcmF0b3IiICk7CgkKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5zdWJzdHJp
bmdCZWZvcmUoc3RyLCBzZXBhcmF0b3IpOwoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwg
InZhbHVlIiwgdmFsdWUgKTsKCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChF
eGNlcHRpb24gZSkKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
