<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">leftPad</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CQoJaW50CXNpemUgPSBJRGF0YVV0aWwuZ2V0SW50KCBwaXBlbGluZUN1cnNvciwgInNpemUi
LCAwICk7CgoJU3RyaW5nIHZhbHVlID0gU3RyaW5nVXRpbHMubGVmdFBhZChzdHIsIHNpemUpOwoJ
SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJSURh
dGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInZhbHVlIiwgdmFsdWUgKTsKCglwaXBlbGlu
ZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChFeGNlcHRpb24gZSkKewoJdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
