<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">joinWithSeparatorAndIndex</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmdbXSBhcnJheSA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheSggcGlwZWxpbmVDdXJz
b3IsICJhcnJheSIgKTsKCVN0cmluZyBzZXBhcmF0b3IgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBw
aXBlbGluZUN1cnNvciwgInNlcGFyYXRvciIgKTsKCWludAlzdGFydEluZGV4ID0gSURhdGFVdGls
LmdldEludCggcGlwZWxpbmVDdXJzb3IsICJzdGFydEluZGV4IiwgMCApOwoJaW50CWVuZEluZGV4
ID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJzb3IsICJlbmRJbmRleCIsIDAgKTsKCglT
dHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5qb2luKGFycmF5LCBzZXBhcmF0b3IsIHN0YXJ0SW5k
ZXgsIGVuZEluZGV4KTsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ2YWx1ZSIsIHZh
bHVlICk7CgoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0aW9uIGUp
CnsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9Cg==</value>
</Values>
