<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">indexOfDifference</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyMSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAic3Ry
MSIgKTsKCVN0cmluZwlzdHIyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJzdHIyIiApOwoJCgoJaW50IHZhbHVlID0gU3RyaW5nVXRpbHMuaW5kZXhPZkRpZmZlcmVuY2Uo
c3RyMSwgc3RyMik7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUiLCB2YWx1
ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4Y2VwdGlvbiBlKQp7
Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
