<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substring</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglpbnQJc3RhcnQgPSBJRGF0YVV0aWwuZ2V0SW50KCBwaXBlbGluZUN1cnNvciwgInN0YXJ0
IiwgMCApOwoJCgoJU3RyaW5nIHZhbHVlID0gU3RyaW5nVXRpbHMuc3Vic3RyaW5nKHN0ciwgc3Rh
cnQpOwoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OwoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInZhbHVlIiwgdmFsdWUgKTsKCglw
aXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChFeGNlcHRpb24gZSkKewoJdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
