<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">splitPreserveAllTokensWithSeparatorAndMax</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc2VwYXJhdG9yQ2hhcnMgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgInNlcGFyYXRvckNoYXJzIiApOwoJaW50CW1heCA9IElEYXRhVXRpbC5nZXRJbnQo
IHBpcGVsaW5lQ3Vyc29yLCAibWF4IiwgMCApOwoKCVN0cmluZ1tdIHZhbHVlID0gU3RyaW5nVXRp
bHMuc3BsaXRQcmVzZXJ2ZUFsbFRva2VucyhzdHIsIHNlcGFyYXRvckNoYXJzLCBtYXgpOwoJSURh
dGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInZhbHVlIiwgdmFsdWUgKTsKCglwaXBlbGluZUN1
cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChFeGNlcHRpb24gZSkKewoJdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
