<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">initialsWithDelimiters</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsNCglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJz
dHIiICk7DQoJU3RyaW5nW10gZGVsaW1pdGVycyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShw
aXBlbGluZUN1cnNvciwgImRlbGltaXRlcnMiKTsNCg0KCWNoYXJbXSBkZWxpbWl0ZXJzQ2hhciA9
IG5ldyBjaGFyW2RlbGltaXRlcnMubGVuZ3RoXTsNCglmb3IgKGludCBpPTA7IGk8ZGVsaW1pdGVy
cy5sZW5ndGg7IGkrKyl7DQoJCWRlbGltaXRlcnNDaGFyW2ldID0gZGVsaW1pdGVyc1tpXS5jaGFy
QXQoMCk7DQoJfQ0KCVN0cmluZyB2YWx1ZSA9IFdvcmRVdGlscy5pbml0aWFscyhzdHIsIGRlbGlt
aXRlcnNDaGFyKTsNCglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInZhbHVlIiwgdmFs
dWUgKTsNCg0KCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KfQ0KY2F0Y2goRXhjZXB0aW9u
IGUpDQp7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7DQp9CQ==</value>
</Values>
