<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">substringAfter</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc2VwYXJhdG9yID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJzZXBhcmF0b3IiICk7CgkKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5zdWJzdHJp
bmdBZnRlcihzdHIsIHNlcGFyYXRvcik7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0g
cGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAi
dmFsdWUiLCB2YWx1ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4
Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
