<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">countMatches</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CQoJU3RyaW5nCXN1YiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAi
c3ViIiApOwkKCglpbnQgY291bnQgPSBTdHJpbmdVdGlscy5jb3VudE1hdGNoZXMoc3RyLCBzdWIp
OwoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJ
SURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImNvdW50IiwgY291bnQgKTsKCglwaXBl
bGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKfQpjYXRjaChFeGNlcHRpb24gZSkKewoJdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K</value>
</Values>
