<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mid</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglpbnQJbGVuID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJzb3IsICJsZW4iLCAw
ICk7CglpbnQJcG9zID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJzb3IsICJwb3MiLCAw
ICk7CgkKCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5taWQoc3RyLCBwb3MsIGxlbik7CglJ
RGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CglJRGF0
YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUiLCB2YWx1ZSApOwoKCXBpcGVsaW5l
Q3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
