<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replaceWithMax</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJcmVwbCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAi
cmVwbCIgKTsKCVN0cmluZwl3aXRoID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJ3aXRoIiApOwoJaW50CW1heCA9IElEYXRhVXRpbC5nZXRJbnQoIHBpcGVsaW5lQ3Vyc29y
LCAibWF4IiwgMCk7CgoJU3RyaW5nIHZhbHVlID0gU3RyaW5nVXRpbHMucmVwbGFjZShzdHIsIHJl
cGwsIHdpdGgsIG1heCk7CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUiLCB2
YWx1ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwp9CmNhdGNoKEV4Y2VwdGlvbiBl
KQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQo=</value>
</Values>
