<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">indexOfAnyBut</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdHIi
ICk7CglTdHJpbmcJc2VhcmNoU3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJzZWFyY2hTdHIiICk7CgkKCglpbnQgaW5kZXggPSBTdHJpbmdVdGlscy5pbmRleE9mQW55
QnV0KHN0ciwgc2VhcmNoU3RyKTsKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJpbmRl
eCIsIGluZGV4ICk7CgoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0
aW9uIGUpCnsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9Cg==</value>
</Values>
