<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">abbreviate</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5DQp7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsNCglTdHJpbmcJc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJz
dHIiICk7DQoJaW50CW1heFdpZHRoID0gSURhdGFVdGlsLmdldEludChwaXBlbGluZUN1cnNvciwg
Im1heFdpZHRoIiwgMCk7DQoNCglTdHJpbmcgdmFsdWUgPSBTdHJpbmdVdGlscy5hYmJyZXZpYXRl
KHN0ciwgbWF4V2lkdGgpOw0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGlu
ZS5nZXRDdXJzb3IoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidmFsdWUi
LCB2YWx1ZSApOwoKCXBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KfQ0KY2F0Y2goRXhjZXB0
aW9uIGUpDQp7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7DQp9DQoJ</value>
</Values>
